### ISSUE TITLE
SSH

### ISSUE THREAD

**Issue by thecomfychair2** [BramRausch/PiPod#2]
First up, love this project! My ipod nano finally gave up the ghost and I can't find anything off the shelf to replace it, so this is perfect!
I have flashed your latest image (Google drive link from the Hackaday page) onto my RaPi Zero, but now I can't seem to ssh to it. Does this image still allow for ssh?
I have tried doing the recommended mods to the Boot text files, and creating a file named 'ssh' in the boot directory, but cannot get a rise out of it.
Cheers in advance!

**Comment by BramRausch** [comment]
Hey, the latest image doesn't have SSH enabled, and all networking services are disabled to start at the boot process because this isn't necessary for normal function, and speeds up the boot time by 30 - 60 seconds. 

I enabled a serial driver instead of the USB ethernet gadget this makes your computer recognize the RPi as a serial device. 

you can use a serial console to log in to the RPi using the following information:
Baudrate: 115200 
Username: pi 
Password: raspberry
The serial port can be found using device-manager.

If you want to use the Wifi functionality you'ill have to enable all network-related services in the system.d configuration.

**Comment by thecomfychair2** [comment]
Perfect, that worked! Thank you very much for your help, and quick response!
